System:
  Name: 'MCTest Regen'
  Version: '0.0.1 Alpha'
  InstallLock: 'install.lock'
  InstallScript: 'website.install'
  Headers:
    FrameworkInfo: true
    SystemInfo: true

MySQL:
  Host: 'localhost'
  User: 'root'
  Pass: 'meiyoumima'
  Database: 'mctest'
  Charset: 'utf8'
  Prefix: 'mctest_'

Template:
  Compiled: '{?WEB_ROOT}/tmp/compiled/'
  Cached: '{?WEB_ROOT}/tmp/cached/'
  Template: '{?WEB_ROOT}/static/template/'

Session:
  # In minutes.
  # In order to save disk space/RAM Usage
  # (if session is stored in memory(tmpFS))
  # 15 or lower is preferred!
  Expire: 15
  Prefix: aDx_ 

Cookie:
  # In minutes.
  # If Expire < 0, the life time of the cookie, is the browser session.
  Expire: 1440
  Prefix: gFs_

URI:
  Rules:
    -
      Pattern: '/'
      Backend: 'website.main'
    -
      Pattern: '/add'
      Backend: 'website.add'
    -
      Pattern: '/static/(.+)'
      Backend: 'Main.Resource'
  Prefix: ''
  Default: 'Main.NotMatched'
  GZip:
    Extensions:
      - 'js'
      - 'css'
      - 'txt'
      - 'htm'
      - 'html'
      - 'xml'
    # Min size that enable gzip compression.
    Size: 0
    Cache: '{?WEB_ROOT}/tmp/cached/'

Lang:
  Default: 'zh-CN'

Runtime:
  Recursive: true
  Require:
  - '{?WEB_ROOT}/runtime/'
